# Generated by Django 5.2.4 on 2025-07-26 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=190)),
                ("code", models.CharField(max_length=20)),
                ("flag", models.URLField()),
            ],
            options={
                "verbose_name": "Ülke",
                "verbose_name_plural": "Ülkeler",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.CharField(max_length=100)),
                ("api_key", models.CharField(max_length=500)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Sağlayıcı",
                "verbose_name_plural": "Sağlayıcılar",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="eSIMPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("validity_days", models.PositiveIntegerField()),
                ("data_amount_mb", models.PositiveIntegerField()),
                ("detail", models.JSONField()),
                ("is_active", models.BooleanField(default=False)),
                ("countries", models.ManyToManyField(to="esim.country")),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="esim.provider"
                    ),
                ),
            ],
            options={
                "verbose_name": "eSIM Paketi",
                "verbose_name_plural": "eSIM Paketleri",
                "ordering": ["-updated_at"],
            },
        ),
    ]
