# Generated by Django 5.2.4 on 2025-07-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esim", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="esimpackage",
            name="external_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
