# Generated by Django 5.2.4 on 2025-07-19 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("esim", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="esimpackage",
            old_name="config",
            new_name="detail",
        ),
    ]
