# Generated by Django 5.2.4 on 2025-07-31 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esim", "0002_esimpackage_external_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackageCountry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=100)),
                (
                    "esim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="esim.esimpackage",
                    ),
                ),
            ],
        ),
    ]
