# Generated by Django 5.2.4 on 2025-07-22 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("esim", "0002_rename_config_esimpackage_detail"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={
                "ordering": ["name"],
                "verbose_name": "Ülke",
                "verbose_name_plural": "Ülkeler",
            },
        ),
        migrations.AlterModelOptions(
            name="esimpackage",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "eSIM Paketi",
                "verbose_name_plural": "eSIM Paketleri",
            },
        ),
        migrations.AlterModelOptions(
            name="provider",
            options={
                "ordering": ["name"],
                "verbose_name": "Sağlayıcı",
                "verbose_name_plural": "Sağlayıcılar",
            },
        ),
    ]
