# Generated by Django 5.2.4 on 2025-07-31 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("esim", "0003_packagecountry"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PackageCountry",
        ),
    ]
