# Generated by Django 5.2.4 on 2025-07-23 17:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esim", "0003_alter_country_options_alter_esimpackage_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="esimpackage",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
