# Generated by Django 5.2.4 on 2025-07-24 23:04

from django.utils.timezone import now
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esim", "0004_alter_esimpackage_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="esimpackage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="provider",
            name="created_at",
            field=models.DateTimeField(default=now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="provider",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="esimpackage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
