# Generated by Django 5.2.4 on 2025-08-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esim", "0004_delete_packagecountry"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="country",
            name="is_regional",
            field=models.BooleanField(default=False),
        ),
    ]
