# Generated by Django 5.2.4 on 2025-08-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esim", "0005_country_is_active_country_is_regional"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="is_global",
            field=models.BooleanField(default=False),
        ),
    ]
