# Generated by Django 5.2.4 on 2025-08-06 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esim", "0006_country_is_global"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfferedPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(max_length=50)),
                ("explanation", models.TextField(max_length=70)),
                (
                    "esim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="esim.esimpackage",
                    ),
                ),
            ],
        ),
    ]
