# Generated by Django 5.2.4 on 2025-08-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esim", "0007_offeredpackage"),
    ]

    operations = [
        migrations.AddField(
            model_name="offeredpackage",
            name="dealer_sale",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="offeredpackage",
            name="end_user_sales",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="offeredpackage",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
