# Generated by Django 5.2.4 on 2025-08-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esim", "0008_offeredpackage_dealer_sale_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="esimpackage",
            name="is_offered",
            field=models.BooleanField(
                default=False, verbose_name="Sunulan Paket olarak işaretle"
            ),
        ),
    ]
