# Generated by Django 5.2.4 on 2025-08-06 14:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esim", "0009_esimpackage_is_offered"),
    ]

    operations = [
        migrations.AddField(
            model_name="offeredpackage",
            name="cost_multiplier",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                max_digits=5,
                verbose_name="Maliyet Çarpanı",
            ),
        ),
        migrations.AddField(
            model_name="offeredpackage",
            name="cost_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Maliyet Fiyatı (API'den Gelen)",
            ),
        ),
        migrations.AddField(
            model_name="offeredpackage",
            name="sale_price",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                editable=False,
                max_digits=12,
                verbose_name="Satış Fiyatı",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="offeredpackage",
            name="sales_multiplier",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                max_digits=5,
                verbose_name="Satış Çarpanı",
            ),
        ),
    ]
