# Generated by Django 5.2.4 on 2025-08-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esim", "0010_offeredpackage_cost_multiplier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offeredpackage",
            name="cost_price",
            field=models.DecimalField(
                decimal_places=2,
                editable=False,
                max_digits=12,
                verbose_name="Maliyet Fiyatı (API'den Gelen)",
            ),
        ),
        migrations.AlterField(
            model_name="offeredpackage",
            name="explanation",
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name="offeredpackage",
            name="title",
            field=models.CharField(max_length=50),
        ),
    ]
