# Generated by Django 5.2.4 on 2025-08-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esim", "0011_alter_offeredpackage_cost_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="offeredpackage",
            name="country",
            field=models.TextField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
