# Generated by Django 5.2.4 on 2025-08-06 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("esim", "0012_offeredpackage_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offeredpackage",
            name="country",
        ),
    ]
