# Generated by Django 5.2.4 on 2025-08-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esim", "0013_remove_offeredpackage_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="esimpackage",
            name="slug",
            field=models.TextField(default=1, max_length=90),
            preserve_default=False,
        ),
    ]
