# Generated by Django 5.2.4 on 2025-08-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_customuser_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Kullanıcının mevcut bakiyesi",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("TRY", "Turkish Lira"),
                ],
                default="USD",
                help_text="Bakiyenin tutulduğu para birimi",
                max_length=3,
            ),
        ),
    ]
