# Generated by Django 5.2.4 on 2025-08-04 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealers", "0003_dealer_secure_id"),
        ("users", "0004_customuser_balance_customuser_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="dealer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="dealers.dealer",
            ),
            preserve_default=False,
        ),
    ]
