# Generated by Django 5.2.4 on 2025-08-04 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealers", "0003_dealer_secure_id"),
        ("users", "0006_alter_customuser_dealer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="dealer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dealers.dealer",
            ),
        ),
    ]
