# Generated by Django 5.2.4 on 2025-08-03 23:52

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dealer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dealer_name", models.TextField(max_length=100)),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Komisyon oranını yüzde olarak giriniz. (Örn: 5.00 = %5)",
                        max_digits=5,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region="TR", unique=True
                    ),
                ),
                ("adress", models.TextField()),
                ("authorized_name", models.TextField()),
                (
                    "dealer_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Kullanıcının mevcut bakiyesi",
                        max_digits=12,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("TRY", "Turkish Lira"),
                        ],
                        default="USD",
                        help_text="Bakiyenin tutulduğu para birimi",
                        max_length=3,
                    ),
                ),
            ],
        ),
    ]
