# Generated by Django 5.2.4 on 2025-08-04 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealer",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
