# Generated by Django 5.2.4 on 2025-08-04 13:54

import app.dealers.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealers", "0002_dealer_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealer",
            name="secure_id",
            field=models.CharField(
                default=app.dealers.utils.generate_base62_id,
                editable=False,
                max_length=12,
                unique=True,
            ),
        ),
    ]
